// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DisplayMatchBetFormController from "./display_match_bet_form_controller"
application.register("display-match-bet-form", DisplayMatchBetFormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
